### ISSUE TITLE
LIS Link Service not being passed gene names it likes

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#11]
resulting in invalid urls and malformed descriptors being returned.
where this gets fixed is negotiable, but we should agree on what exactly is going to get passed in; traditionally it has been the "name" which was basically of the form gensp.whatever-they-called-it 

perhaps it would make sense to switch to passing in "full yuck" at this point, maybe that is what you're doing already but doesn't look like it.

**Comment by sammyjava** [comment]
It's really up to you. But as per a previous convo, I pulled "gensp." from "gensp.whatever-they-called-it" because "gensp.whatever-they-called-it" is not what they called it, which defeats the purpose.

It's a very simple config in web.properties, which was set up as so:
```
attributelink.legumeinfo.Gene.3885.secondaryIdentifier.url=https://legumeinfo.org/feature/Phaseolus/vulgaris/gene/<<attributeValue>>                                                                               
attributelink.legumeinfo.Gene.3885.secondaryIdentifier.text=View this gene on <b>LIS</b>
```
But secondaryIdentifier has changed a bit, and Gene.name is now whatever-they-called-it that comes straight from the GFF Name attribute (which I may have tweaked). My preference would be to use full-yuck for identifiers on any LIS application. Because that's why full yuck.

Here are the mine options, using a common bean example:
```
primaryidentifier   | phavu.G19833.gnm1.ann1.Phvul.003G000100
secondaryidentifier | Phvul.003G000100
name                | PHAVU_003G000100g
```
There is also a symbol field that I'd use for something like REVOLUTA when available, which is almost always never.

Back to you.

**Comment by adf-ncgr** [comment]
OK, to me it looks like you have there is:
secondaryidentifier | what-they(phytozome)-called-it (and what I guess is now what should be present for Name in gff instead of gensp.wtci if you have made these changes as we casually discussed once)
primaryIdentifier | flyck.wtci
name | what someone else (ncbi into us by way of reactome?) decided to call it ("because ncbi")

so let's go for primaryIdentifier as you suggest and I will modify the receiving code to handle gracefully.
thanks!

**Comment by sammyjava** [comment]
Done. Updated the straight attribute link, which already works, and the LIS linkout JSON, with stuff like this:
```
https://legumeinfo.org/gcv2/gene;lis=phavu.G19833.gnm1.ann1.Phvul.001G039200
```

**Comment by adf-ncgr** [comment]
Thanks. I've updated the linkout service to try to be gracefuller; seems to be working as hoped, but let me know if you happen to notice anything that doesn't look right.
