### ISSUE TITLE
the "shareable URLs" for proteins aren't working?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#113]
on at least arachismine and phaseolusmine, if you are on the page of a protein and ask for the shareable URL, it comes up blank. Similarly, if you try to go directly to https://mines.legumeinfo.org/arachismine/protein:arahy.Tifrunner.gnm1.ann1.N179K0.1 a not found error is given (works fine for mrna and cds though)

**Comment by adf-ncgr** [comment]
PS. is there any good reason why the gene page shouldn't provide direct access to the protein sequence(s) like it does for transcript and CDS? Currently, it seems you have to scroll all the way down the gene report page to get to the table of proteins, then go to their pages to get the sequence. (a possible hijack of the bug report, but all related to a user request received)

**Comment by sammyjava** [comment]
I think the reason is that Protein is not a SequenceFeature and they coded that displayer to show SequenceFeatures? But, of course, our CDS is not SequenceFeature, but the displayer works anyway. File a separate issue for me to add Protein to geneStructureDisplayer.jsp if you'd like me to. One could argue that Transcript and CDS are "gene structure" while protein is not, so that may be another reason they didn't include Protein, but I agree we may as well show it so you can grab the sequence.

**Comment by adf-ncgr** [comment]
OK, I guess since we're trying to focus more on bluegenes I may not bother to bother you with updating jsp; looks like in bluegenes you only get a FASTA download option for the feature being reported on which may not be ideal but when we link folks over to JBrowse2 they can get that kind of thing there.

**Comment by sammyjava** [comment]
I don't mind doing legacy updates. And, perhaps we want to provide those associated FASTAs in Bluegenes as well. It just saves a click from clicking over to the other object, which may be why they dropped it.

**Comment by sammyjava** [comment]
This is fixed, with further fixes enabled in 5.1.0.3. I'm redeploying all the prod mines with the update.
