### ISSUE TITLE
regions search on legumemine dropdown has only one choice (A. evenia)

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#132]
If you could only choose one legume to take with you to a desert island you could probably do worse than jointvetch, but we still ought to let the free market decide.

**Comment by sammyjava** [comment]
The free market always makes the worst choices.

**Comment by sammyjava** [comment]
Well that was easy, and a bit surprising. I had missed the phavu description load, so 3885 didn't have any information. I guess because there are sequences associated with it, it wanted to list it on the selector, but didn't have a Genus or species. (The Genus-level organisms don't seem to break it.) No idea why that source got dropped from project.xml, just an exuberant cut I guess.

**Comment by adf-ncgr** [comment]
That's getting to be quite a dropdown list- thanks for restoring our freedom of choice!
