### ISSUE TITLE
Rerun transfer-sequences

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#133]
In working that example query for the folks interested in 2kb upstream flanking regions, I used the example set of Cajanus genes and noticed that only 2 of them actually returned flanking regions in the query I made. As far as I can tell, it may be because three of the example genes are on scaffolds and only 2 on chromosomes, but this is just a conjecture. In any case, although genes on supercontigs are becoming more exceptional as assemblies become better, I don't think we ought to treat them as second class citizens. They didn't even seem to get an embedded JBrowse- now that's harsh!

**Comment by sammyjava** [comment]
Turns out I'd created flanking regions AFTER running transfer-sequences, so here's one of my patented to-do checklists:
- [x] aeschynomenemine
- [x] arachismine
- [x] cajanusmine
- [x] cicermine
- [x] glycinemine
- [x] legumemine
- [x] lensmine
- [x] lupinusmine
- [x] medicagomine
- [x] minimine
- [x] phaseolusmine
- [x] vignamine
