### ISSUE TITLE
!! GlycineMine Keyword search not working!!

### ISSUE THREAD

**Issue by jd-campbell** [legumeinfo/mine-issues#159]
@adf-ncgr 

Glycinemine keyword search is not working not matter what I enter into the text box.

**Comment by jd-campbell** [comment]
Email exchange from @adf-ncgr : "looks like it is not just glycinemine, so probably the solr search daemon has fallen over again. I will restart it and contemplate what is causing these issues..."

**Comment by adf-ncgr** [comment]
another "OOM" (out of memory) issue on the solr server end. I had increased the memory to the host VM thinking that would  sort it, but I may need to adjust solr config instead. In any case, I've restarted it for now.

**Comment by adf-ncgr** [comment]
OK, I think I've ascertained:
1. that the solr installation was using a default configuration that limited max memory on the JVM running solr to 512m, which is probably insufficient for some of our queries
2. how to modify the JVM options so that they are used in the systemctl started application (modify variables in /etc/default/solr.in.sh)

per the info returned using https://solr.apache.org/guide/8_5/jvm-settings.html#checking-jvm-settings I think the change has been effected, hopefully the increase to 8g will mean a more stable experience for all...
