### ISSUE TITLE
GlycineMine External Link to Ensembl Plants Failing

### ISSUE THREAD

**Issue by maxglycine** [legumeinfo/mine-issues#177]
I was looking at the GlycineMine report for Glyma.12G066300 and saw the “External Links” section at the bottom of the right side

I clicked on the “Ensembl Plants” link and it failed.  I tried with the suggested “GLYMA_12G066300” and it worked.

Need to fix or remove the link

@nathanweeks, @adf-ncgr , @jd-campbell, @StevenCannon-USDA

**Comment by adf-ncgr** [comment]
Thanks @maxglycine; it looks like Sam added "ensemblName" as an attribute of gene in version 5.1.0.4 of the datamodel, along with some very special case logic to set it for various genomes when loading their annotations. But, since we haven't released 5.1.0.4 mines, I'm not sure why that link is being offered in the web app. I'll see about removing it for now and we may or may not decide we want it later when the data supports it (looks like the real reason he added ensemblName may have been to better support PlantReactome pathway loading, though I'm not %100 sure about that).

**Comment by adf-ncgr** [comment]
should be fixed on GlycineMine. Probably still needs to be fixed on other mines so I will leave this issue open until I've handled for the others.

**Comment by adf-ncgr** [comment]
OK, I think all of the production mines have now been fixed with respect to the broken Ensembl Plants link. Probably further tweaking on links and linkouts would be warranted, but I'll close this issue.
