### ISSUE TITLE
links to phylotree on (at least) ChickpeaMine are broken

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#30]
see https://mines.legumeinfo.org/chickpeamine/genefamily:legfed_v1_0.L_LC2G7V
which seem to want to link internally rather than externally to legumeinfo.org

**Comment by sammyjava** [comment]
Fixed on dev, typo in web.properties (oddly not on any other mines). But not updateable on production since I don't have a 5.0.2 ChickpeaMine built yet. It will work on ChickpeaMine v2.1. (Let me know if you want me to bump ChickpeaMine up in the priority list with your Doug biz going on. I'm working on SoyMine which will take a while, but Steven requested that as the next one.)
