### ISSUE TITLE
MedicMine: lists of genes that individually have expression barcharts don't always show heatmaps when combined on list page 

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#36]
e.g. Medtr6g017260 and Medtr4g075040

**Comment by sammyjava** [comment]
Yup, client-side bug. I'll fix it when fisher is done.

**Comment by sammyjava** [comment]
Fixed. I believe it is only a bug with one- or two-gene lists, because there used to be a bug in CanvasXpress that broke the heatmap with less than three rows and I did a bad job of indicating that heatmaps were disabled for less than three genes. That is no longer a bug, so now you can view a heatmap with as few as one expressive gene.
