### ISSUE TITLE
Links from LIS gene family phylograms to mines shows "No matches found"

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/mine-issues#55]
Links from LIS gene family phylograms to mines results in "No matches found for vigan.Vang11g14690Could not resolve a Gene for identifier: vigan.Vang11g14690"

Example gene family page:
https://legumeinfo.org/chado_phylotree/legfed_v1_0.L_7P59NX?hilite_node=arahy.0008XH.1
From here links to:
https://mines.legumeinfo.org/legumemine/portal.do?class=Gene&externalids=glyma.Glyma.10G126700
https://mines.legumeinfo.org/legumemine/portal.do?class=Gene&externalids=arahy.0008XH

From https://legumeinfo.org/chado_phylotree/legfed_v1_0.L_BN86MY
to:  
https://mines.legumeinfo.org/legumemine/portal.do?class=Gene&externalids=arahy.CAM23Q
https://mines.legumeinfo.org/legumemine/portal.do?class=Gene&externalids=arahy.LBE3WY
https://mines.legumeinfo.org/legumemine/portal.do?class=Gene&externalids=medtr.Medtr4g128840 
https://mines.legumeinfo.org/legumemine/portal.do?class=Gene&externalids=vigan.Vang11g14690
(**Works**) https://mines.legumeinfo.org/legumemine/portal.do?class=Gene&externalids=cicar.CDCFrontier.Ca_03273 

Haven't tested extensively beyond this.

**Comment by adf-ncgr** [comment]
I'm not actually sure this is a mine issue. I think it may be due to the fact that the linkout code is still using the older naming convention where we had "lite yuck" with gensp prefixes instead of either "full yuck" or "no yuck". Haven't had a chance to look at it more closely to confirm this is the issue.

With respect to the question of the legacy phylograms, at least for the time being they will persist on "legacy.legumeinfo.org" but also they will be available via the new funnotate per legumeinfo/Funnotate#21

**Comment by sammyjava** [comment]
Ahh, correct, I was thinking of keyword search rather than links, like https://mines.legumeinfo.org/beanmine/gene:phaac.Frijol_Bayo.gnm1.ann1.Phacu.CVR.002G040500 which are configured to use primaryIdentifier. So I'll switch this back to you @adf-ncgr and you can have your way with it.

**Comment by adf-ncgr** [comment]
forgot to mention in today's meeting but I had a look at updating the linkout code on lis-stage to use uniquenames (aka full yuck) to go to intermine. Generally this works, but there are some cases where either the uniquenames need to be fixed in chado (should be easy to do) or the version of the genome stored in chado is not identical to what is loaded into the mine. Examples of the latter include arahy (gnm1 in chado gnm2 in mine) and vigun (gnm1 in chado gnm2 in mine). Not sure what the best thing to do about this is, but technically the problem is not with chado per se but with the fact that the trees use the old versions of annotations (so in fact they are proteins that are unlinkable to intermine unless we fudge things and assume that gnm2 versions are equivalent to gnm1 versions which is probably true in most cases but not all). anyway, that's the current status.

**Comment by sammyjava** [comment]
I've been loading older assemblies as well as the most recent lately, but in the genus-specific mines, not LegumeMine. Which I guess is the problem. But shouldn't the linkout service be weaned from chado, anyway, since it is soon to be deprecated?

**Comment by adf-ncgr** [comment]
They should indeed be weaned- defining the new linkout protocol has been a TODO for quite some time, and it's almost certainly my fault that it has not progressed; but I think the basic problem will remain until we rebuild the trees (which is also on a TODO list)

**Comment by adf-ncgr** [comment]
OK, this is fixed in the sense that when the versions of genomes used in the trees and in LegumeMine correspond, it works. However, some of the genomes that now have version mismatch issues include soybean, common bean, peanut and cowpea, so that's less than ideal but at least it's an accurate portrayal of reality.
