### ISSUE TITLE
keyword indexing on legumemine may need refresh?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#64]
not sure if that is the real cause of the following behavior:
there is a gene family legfed_v1_0.L_ZZWVY4 with descriptor "protein SRG1-like [Glycine max]..." which is present in the mine
https://mines.legumeinfo.org/legumemine/report.do?id=112000004
but not reachable using keyword searches for SRG1 or "SRG1-like" or legfed_v1_0.L_ZZWVY4, etc.

I noticed this when trying to search via https://funnotate.legumeinfo.org/?search but also came up empty through the mine interface itself, so must be an issue there. But some gene families must be keyword-indexed as I do get results for others
(e.g. legfed_v1_0.L_4RYTMP comes back no problem); which seems weird- can you get a partial solr index if there's some error midway through? or is there something fundamentally non keywordish about the gene family I happened to be looking at?

**Comment by sammyjava** [comment]
Yeah, I dunno, I'm deep into figuring out what's going on with soymine's index. I blew away all the partial-match config and am indexing it from scratch to see if that doesn't crash out. Could be I just need to throw more resources at the VM but it seems to have plenty while it's indexing. I'll wait on resolving that before I hit legumemine since they may be related.

**Comment by adf-ncgr** [comment]
sounds good, let me know if you need any more info or another pair of eyes on anything; I ought to learn more about solr indexing

**Comment by sammyjava** [comment]
Closing this since I'm building a new LegumeMine.
